version: '2'

services:

    db:
        image: mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: secretpassword

    adminer:
        image: adminer
        ports:
            - 8180:8080

    portainer:
        image: portainer/portainer
        ports:
          - 9000:9000
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    watchtower:
      image: v2tec/watchtower

    mosquitto:
      image: eclipse-mosquitto
      ports:
        - 1883:1883
        - 9001:9001
      volumes:
        - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
